export const enquiryHeaders = {
  Vehicle: [
    "Full Name",
    "Email",
    "Phone",
    "Vehicle Number",
    "Location/Pincode",
    "Sub Service",
    "Uploaded File",
  ],
  Health: [
    "Full Name",
    "Email",
    "Phone",
    "DOB",
    "Location/Pincode",
    "Occupation",
    "Annual Income",
    "Family Members",    
    "Sub Service",
    "Uploaded File",
  ],
  "Books-Stationary": [
    "Full Name",
    "Email",
    "Phone",
    "School Name",
    "Address",
    "Sub Service",
    "Uploaded File",
  ],
  Auditing: [
    "Full Name",
    "Email",
    "Phone",
    "Company Name",
    "Turnover",
    "Year Established",
    "Sub Service",
    "Uploaded File",
  ],
};
